### PR TITLE
add project location and more specificity to those with

### PR DESCRIPTION
**Pull request by loganpowell**
Lookin' pretty!

### CODE REVIEW

**Comment by pshrmn** [comment]
Looks good, thanks!

I'll take a look at adding the `data-line`. Was the tutorial otherwise pretty useful?

**Comment by loganpowell** [comment]
Yes, very helpful. A very different paradigm from RR. I think you may want to sell some of the added benefits of the centralized approach for those who will need convincing that this is more powerful/efficient/<input your killer feature here> ykwim? 

Still working on it. I'm a bit scattered as I'm doing this intermingled with regular "work" :)

**Comment by loganpowell** [comment]
Perhaps a catchy tagline like "let your data do the talking" or something like that.

**Comment by pshrmn** [comment]
I ended up just forking `react-prism` so I could add the `data-line` functionality. I added a few highlights to test it out. I can go back later to figure out where else they are necessary, but if you want to take a stab at it, go ahead.

**Comment by loganpowell** [comment]
Will do

**Pull request merged**
