### PR TITLE
add location to first four tutorials

### PR DESCRIPTION
**Pull request by loganpowell**
apologies for the big diff! I used beautify :( I only added a few lines as we discussed in https://github.com/pshrmn/curi/issues/22#issuecomment-360519919

I'm such a newb. Forgive me if I should have done this on a branch. I've only made like 3 PRs in my life.

### CODE REVIEW

**Comment by pshrmn** [comment]
No worries about the diff, I'll fix it up. I use `pretty-quick` to automatically run `prettier` on the code before a commit. I must have something incorrectly configured since that didn't run for you (or maybe you just didn't `npm install` before making the PR?).

The branch thing doesn't matter at all on my end. It only really complicates things for you if you wanted to create another PR before this is merged because you would have to checkout from a remote branch.

**Comment by loganpowell** [comment]
> or maybe you just didn't npm install before making the PR?

Yep, nope :D

**Comment by pshrmn** [comment]
Ah, shoot, `prettier` couldn't fix everything `beautify`did. I just reset this to its original state (minus `prettier` switching single quotes to doubles). Would you mind pulling and re-adding the file descriptors?
```bash
git pull origin master
```

**Comment by loganpowell** [comment]
Stupid question: Will that pull from my repo or yours?

**Comment by pshrmn** [comment]
Not a stupid question. Assuming that you cloned it locally from your fork, It will pull from yours.

You can use `git remote -v` to see the remotes that you have. From what I have generally seen, the pattern with forks is that you add an `upstream` remote to "real" repo if you need to pull in changes (`git remote add upstream https://github.com/pshrmn/curi.git`).

**Comment by loganpowell** [comment]
I think I figured it out from [stackexchange](https://stackoverflow.com/a/9646323/7253358)

**Comment by loganpowell** [comment]
quick question, do you know if I can get access to the `prism` [`data-line`](https://github.com/oswaldoacauan/ghostium/issues/109#issuecomment-48852208) attribute to highlight new lines of code? That's tripping me up just a little. Not a big deal either way.

**Pull request closed without merging**
